### ISSUE TITLE
Available on composer?

### ISSUE THREAD

**Issue by Jono20201** [haakym/uk-bank-holidays#1]
Hi,

Is this package available on composer? I tried `composer require haakym/uk-bank-holidays` without luck.

Thanks.

**Comment by haakym** [comment]
Hi @Jono20201 

Sorry for the late reply. No, I haven't added it to packagist. Couple of options for you:

1. You could pull it in as a respository in composer https://getcomposer.org/doc/05-repositories.md 
2. Fork it and add it yourself to packagist
3. Use another package like this one https://packagist.org/packages/citco/carbon which extends carbon.

Option 3 is probably the best idea provided the package offers the functionality you require.

Hope this helps!
